config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
    resources :tasks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks

  validates_presence_of :name
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates_presence_of :description

  def toggle_completed!
    update(completed: !completed)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks
    @task = Task.new
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

    def list_params
      params.require(:list).permit(:name)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @task = Task.new(task_params)
    @task.completed = false
    @task.list = List.find(params[:list_id])

    if @task.save
      redirect_to list_path(@task.list.id)
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.toggle_completed!

    redirect_to list_path(@task.list.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @list = @task.list
    @task.destroy

    redirect_to list_path(@list)
  end

  private

    def task_params
      params.require(:task).permit(:description, :completed, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>List Index</h1>
<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name, list_path(list.id) %> - 
      <%= link_to "Delete", list_path(list.id), method: :delete %>
    </li>
  <% end %>
</ul>
<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :submit %>
  <%= f.submit :submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<ul>
  <%= render @tasks %>
</ul>

<%= form_for [ @list, @task ] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />
  <%= f.label :submit %>
  <%= f.submit :submit %>
<% end %>
<%= link_to "Delete", list_path(@list), method: :delete %>
<br />
<%= link_to "Home", lists_path %>

app/views/tasks/_task.html.erb
<li class="<%= 'completed' if task.completed %>">
  <%= task.description %>
  <% if task.completed %>
    <%= link_to "Mark incomplete", list_task_path(task.list_id, task.id), method: :put %>
  <% else %>
    <%= link_to "Complete", list_task_path(task.list_id, task.id), method: :put %>
  <% end %>
  <%= link_to "Remove", list_task_path(task.list_id, task.id), method: :delete %>
</li>